### ISSUE TITLE
Wrong encoding inside K. 1247 ? 

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#13]
Dear @chhomkunthea, 

I found this strange encoding on K. 1247 at the xml line 135: 
```
<lb n="B17"/>der· tai <num value="2">II</num> ku rok· <num value="1">Iseg</num> pau tai
```
Should `seg` really be inside the `<num>`tag? Can you check it please? 

Best,

**Comment by arlogriffiths** [comment]
@chhomkunthea : please react to this.

**Comment by chhomkunthea** [comment]
Dear Axelle,

The ‘seg’ inside ‘num’ was a mistake. I’ve just corrected that. Thank you.

See you,
Kunthea
