### ISSUE TITLE
revise K1298.xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-khmer-epigraphy#14]
I have just made a commit that involves a correction to the txt file for K. 499 and comments on the xml file for K. 1298. See [https://github.com/erc-dharma/tfc-khmer-epigraphy/commit/49113ae3e36323f1357067a01a4b316a00aaf489](url) and [https://github.com/erc-dharma/tfc-khmer-epigraphy/blob/master/texts/xml-provisional/Kunthea/K1298.xml](url).

@chhomkunthea : I have inserted a number of comments `<!-- argr: ... -->` into your recently committed version of K1298.xml. I have found no serious errors of encoding, but note that you take only the bare minimum from the source txt file. You need from now on to reproduce all philologically relevant observations from the txt files, and you need to encode variant readings systematically. That is a high priority. It will also be good to start making a habit of encode translations and bibliography

@dominiquesoutif : nous allons avoir besoin de renseignements plus systématiques sur le membre du CIK qui a fait le travail dans chaque fichier .txt dit "vérifié par CIK". La logique des éditions EpiDoc demande que soit rendu explicite la prise de responsabilité, et de fait @dg2018 et @arlogriffiths ont d'habitude signé les fichiers dont ils sont responsables. Je présume que c'était toi pour K. 1298. Serait-il possible que tu repasses le corpus txt et insères une indication du membre CIK responsable quand tu le sais et quand cela n'est pas encore indiqué dans le fichier? Cela alègera le travail pour Kunthea (et Chloé). **Ne pas oublier de faire un git pull avant d'aborder ce travail, et un git add/commit/push après que tu l'auras bouclé!** 

@dg2018 et @dominiquesoutif : si vous aussi, vous pouviez aider à encadrer le travail de Kunthea en révisant de cette façon quelques fichiers xml, cela serait une contribution précieuse.

**Comment by arlogriffiths** [comment]
@chhomkunthea : your latest revision is now going in the right direction! I have just pushed my new round of comments. There are still  quite a lot of them, but now they are more about how you encode than about how you/we read the inscription itself. And it is nice to see that you have conulsted the EG on several points, although there are also still several points where you need to absord more thoroughly what the EG prescribes. Please discuss separately (by email) with @dominiquesoutif about issues of interpretation. Once you have a next draft ready, inform us here, and we could ask Daniel to take a look.

**Comment by arlogriffiths** [comment]
@chhomkunthea : can this be closed now?

**Comment by chhomkunthea** [comment]
A reply from D. Soutif has been added to the file.

**Comment by chhomkunthea** [comment]
A reply from D. Soutif has been added to the file.

**Comment by arlogriffiths** [comment]
@chhomkunthea : can you close this issue now?
