### ISSUE TITLE
use of encoding log

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-khmer-epigraphy#15]
Dear all! 

Note that the encoding log was converted to .md format by Axelle a few weeks ago, to give the display you can see [here](https://github.com/erc-dharma/tfc-khmer-epigraphy/blob/master/texts/CIK_encoding_log.md). Just open the md file [https://github.com/erc-dharma/tfc-khmer-epigraphy/blob/master/texts/CIK_encoding_log.md](https://github.com/erc-dharma/tfc-khmer-epigraphy/blob/master/texts/CIK_encoding_log.md) in oXygen and fill it in as you were previously doing in txt. The txt file has been moved to the archive.

@dg2018 : I have incorporated your four log entries into the .md file before archiving the .txt.

@chloechollet and @chhomkunthea : if you have been adding entries to the .txt rather than the .md in recent weeks, then we have to check if all your entries have been correctly applied also ion the md. But I don't recall seeing any changes to the .txt in your recent commits.

Please respond with a simple "ok" if you have seen this and require no further guidance.

**Comment by ajaniak** [comment]
Dear all, 

A [basic guide for markdown](https://github.com/erc-dharma/project-documentation/blob/master/guides/github-issuetracker/UsingMarkdownSyntax_v01.md ) is available in the project-documentation repository. 

Best,

**Comment by chhomkunthea** [comment]
ok

**Comment by chloechollet** [comment]
Ok!
