### ISSUE TITLE
moving of CIK-TXT incomplete?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-khmer-epigraphy#16]
@ajaniak : why do I still see CIK-TXT here?

<img width="990" alt="Capture d’écran 2020-05-15 à 13 51 44" src="https://user-images.githubusercontent.com/835603/82047570-505ff600-96b3-11ea-9d60-9bc661b715c7.png">

**Comment by ajaniak** [comment]
Moi, je n'ai rien. Mais c'est probablement lié au commit de Kunthea https://github.com/erc-dharma/tfc-khmer-epigraphy/commit/16edd377bc2a573f81a4b25900328336d053f66e qui contient des fichiers texts et qui est postérieur au déplacement du dossier CIK-txt

**Comment by arlogriffiths** [comment]
ok, problem seems to have gone away
