### ISSUE TITLE
revise K0003.xml

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-khmer-epigraphy#17]
dear @chhomkunthea — I have just finished a first round of revision of reading and encoding this inscription, and pused the revised file (as well as a first set of changes to the txt file, although we'll have to update it systematically as we wrok through the xml edition together). 

Please make all the changes that are required globally:

- encoding of āryā with `<l n="ab"/>` and `<l n="cd"/>`
- use of `<space/>` instead of underscore while avoiding unwanted typed spaces when `<space/>` falls in mid word

We will go through my other comments in the file during our first "Mekong" session on Monday. If I have time, I will add a draft English translation during the weekend.

Sending this message also to @dominiquesoutif and @dg2018  for their information.

**Comment by chhomkunthea** [comment]
OK, as I said in my previous email, I’ll work on it soon, at this weekend.

See you next Monday,
Kunthea

**Comment by chhomkunthea** [comment]
The file has been changed accordingly.

**Comment by chhomkunthea** [comment]
The file has been changed accordingly.

**Comment by chhomkunthea** [comment]
File modified.

**Comment by chhomkunthea** [comment]
Modification completed.

**Comment by chhomkunthea** [comment]
Close issue

**Comment by chhomkunthea** [comment]
close

**Comment by chhomkunthea** [comment]
Close

**Comment by chhomkunthea** [comment]
Close issue
