### ISSUE TITLE
Bibliography problem K0410.xml

### ISSUE THREAD

**Issue by chloechollet** [erc-dharma/tfc-khmer-epigraphy#18]
Chère Axelle,

La présentation des balises `<bibl>` pour cette inscription en html montre quelques incohérences que je n'arrive pas à comprendre. Compare ce qui se passe correctement pour Aymonier (dans la bibliographie) avec les présentations bizarres de Cœdès (dans la bibliographie également) ou encore de Griffiths & Soutif (dans le commentaire). 
<img width="1072" alt="Capture d’écran 2020-11-03 à 15 13 15" src="https://user-images.githubusercontent.com/26011299/97995751-380da000-1de7-11eb-9c8a-359ffa00472d.png">

Merci !

Chloé

**Comment by ajaniak** [comment]
Chère Chloé, 

L'identifiant `Coedes1929_01` correspond à deux entrées dans Zotero, c'est pourquoi l'API rapatrie deux dates et affiche la bibliographie suivante: 

Cœdès, George. 1929a. Inscriptions de Dvāravatī, de Çrivijaya et de Lǎvo. Recueil des inscriptions du Siam 2. Bangkok: Institut Royal. 
———. 1929b. Recueil des Inscriptions du Siam, deuxième partie: Inscriptions de Dvāravatī, de Çrīvijaya et de Lăvo. Bangkok: Bangkok Times Press

Il faut changer le shortTitle et le tag de l'une des deux données. Je viens de vérifier l'usage de cette donnée dans les fichiers. Heureusement K0410.xml est le seul à utiliser bib:Coedes1929_01  pour le moment. Puis-je donc te laisser distinguer les deux entrées Zotero? 

Bien à toi

**Comment by chloechollet** [comment]
Chère Axelle,

Merci beaucoup pour l’explication ! Je n’arrive pas encore à utiliser le XSLT de manière autonome pour vérifier le résultat, mais il n’y a en tout cas plus de doublons dans Zotero.

Bien à toi (j’espère que ton confinement se passe bien!)

Chloé

Le 3 nov. 2020 à 16:02, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



Chère Chloé,

L'identifiant Coedes1929_01 correspond à deux entrées dans Zotero, c'est pourquoi l'API rapatrie deux dates et affiche la bibliographie suivante:

Cœdès, George. 1929a. Inscriptions de Dvāravatī, de Çrivijaya et de Lǎvo. Recueil des inscriptions du Siam 2. Bangkok: Institut Royal.
———. 1929b. Recueil des Inscriptions du Siam, deuxième partie: Inscriptions de Dvāravatī, de Çrīvijaya et de Lăvo. Bangkok: Bangkok Times Press

Il faut changer le shortTitle et le tag de l'une des deux données. Je viens de vérifier l'usage de cette donnée dans les fichiers. Heureusement K0410.xml est le seul à utiliser bib:Coedes1929_01 pour le moment. Puis-je donc te laisser distinguer les deux entrées Zotero?

Bien à toi

**Comment by arlogriffiths** [comment]
J'ai pullé et retesté la présentation html de K0410, et les problèmes sont résolus!
