### ISSUE TITLE
Display problem in K0178.xml

### ISSUE THREAD

**Issue by chloechollet** [erc-dharma/tfc-khmer-epigraphy#20]
- code: `kantrum<unclear>·</unclear><g type="circleMed">.</g> niya<choice><sic>n</sic><corr>m</corr></choice>a`
- display: 
<img width="875" alt="Capture d’écran 2021-01-19 à 15 56 55" src="https://user-images.githubusercontent.com/26011299/105051860-7b36f100-5a6f-11eb-9864-858063f20ea6.png">
- Can you sort this out @ajaniak ?

**Comment by ajaniak** [comment]
Dear @chloechollet, 

I am not sure what you want me to sort. Is it the fact that the `<g type="circleMed">.</g>` is displayed as `|`? 
<img width="700" alt="Capture d’écran 2021-01-19 à 16 10 40" src="https://user-images.githubusercontent.com/33328906/105053136-e9c87e80-5a70-11eb-93ff-360ec29ae1c3.png">

can you give me more precision?

**Comment by arlogriffiths** [comment]
we are seeing not (·)| but (·| in the display on our side — generated with XLST in Oxygen.

<img width="163" alt="Capture d’écran 2021-01-19 à 15 56 25" src="https://user-images.githubusercontent.com/835603/105054066-de298780-5a71-11eb-910a-0daf0439ea7c.png">


display on your side is different!

**Comment by ajaniak** [comment]
Do you have the last version of the XSLT on your computer? 
My version of the output as well as the automated html are both with `(·)| ` and checking the codes history, this issue should have been resolved with the commit made the 4/11/2020.

**Comment by chloechollet** [comment]
My bad. I’ve just done a git pull on project-documentation and the problem seems to have been resolved on the new html version.
