### ISSUE TITLE
missing ) at juncture between <unclear> and <seg>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-khmer-epigraphy#21]
This concerns K1176.xml.

- code: `<l n="d"><unclear>nīla</unclear><seg met="=="><gap reason="lost" quantity="2" unit="character"/></seg> śi<unclear>lā</unclear>may<unclear>ī</unclear></l>`
- display: 
<img width="158" alt="Capture d’écran 2021-01-29 à 12 07 02" src="https://user-images.githubusercontent.com/835603/106267860-8e458000-622a-11eb-8954-1a8ad902f4b0.png">

@ajaniak : I expect a ")" after nīla. Is there a bug in the transformation code?

**Comment by ajaniak** [comment]
I have updated the code to resolve this case. You can update the project-documentation or relaunch the editorial workflow  to access the new output.

**Comment by arlogriffiths** [comment]
Thanks. Can you remind me how I relaunch the editorial workflow?

**Comment by ajaniak** [comment]
2 possibilities to do it : 
- you can do it with a **git push** that will run the workflow by default
- you can go to any repository of your choice, go to the [tab action](https://github.com/erc-dharma/tfc-khmer-epigraphy/actions), then select any run in the list such as [this one](https://github.com/erc-dharma/tfc-khmer-epigraphy/actions/runs/518446195), and click on the button at the right corner `re-run jobs` and click on `re-run jobs` in the list.

I have added links to help you find the different section I am mentioning and a screen shoot to find the button. Let me know if that is enough to let you do it on your own. 

<img width="1371" alt="Capture d’écran 2021-01-29 à 15 12 40" src="https://user-images.githubusercontent.com/33328906/106285218-7da20380-6244-11eb-8466-89f328fb6b00.png">

**Comment by arlogriffiths** [comment]
thanks! (and sorry for the late response.)
