### ISSUE TITLE
Problem with display of III

### ISSUE THREAD

**Issue by chloechollet** [erc-dharma/tfc-khmer-epigraphy#22]
Hello Axelle,
J'ai un problème avec ce bout de code : `sre tl<unclear>o</unclear>ṅ· <num value="3"><g type="numeral">III</g></num> `. 
Le display est : 
<img width="98" alt="Capture d’écran 2021-03-09 à 20 22 44" src="https://user-images.githubusercontent.com/26011299/110477218-32043480-80e3-11eb-88f9-76858962b737.png">

Or, il faudrait avoir III au lieu de II.

**Comment by chloechollet** [comment]
Et pour être plus claire, les trois lettres majuscules i doivent apparaître en tant que telles et non pas être remplacées par des barres verticales.

**Comment by chloechollet** [comment]
(Et cela s'applique à tous les i majuscules en `<num>`)

**Comment by ajaniak** [comment]
Salut Chloé, 

Je viens de modifier l'ordre sur le display de l'élément `<g>`. Une partie du code repose sur une recherche de caractères tandis qu'une autre fonctionne sur les attributs et la structuration, du coup le résultat n'est pas très stable. Normalement, le changement de position dans le code devrait permettre d'éviter que les `<num>`soit en chiffres romains plutôt qu' `|`. 
Tu peux faire un git pull ou relancer le pipeline, selon le système que tu utilises. 
Peux-tu me confirmer que le résultat est bien celui que tu attendais s'il te plait?

**Comment by chloechollet** [comment]
Cela semble bon merci beaucoup !
