### ISSUE TITLE
Language code "eng"

### ISSUE THREAD

**Issue by chloechollet** [erc-dharma/tfc-khmer-epigraphy#23]
code: `<div type="translation" xml:lang="eng" source="bib:Goodall2020_01">` est refusé par le schéma. En revanche, si je mets "en" le schéma est accepté. Or, selon EGC app. D, le code à mettre est bien "eng".

**Comment by ajaniak** [comment]
Ce n'est pas tant un problème sur la syntaxe du code eng, mais le fait que `@xml:lang` n'est pas nécessaire si tu déclares que la langue est anglais, car le fichier est par défaut en anglais. Tu ne dois déclarer que les autres langues. Dans le cas présent, tu dois simplement encoder : `<div type="translation" source="bib:Goodall2020_01">`.
(Voir EGD, 9.2.1)
Le schéma invalide ce cas pour être essayer d'uniformiser les pratiques.

**Comment by arlogriffiths** [comment]
nous en avons pris note, merci!
