### ISSUE TITLE
Merging subfolders

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/tfc-khmer-epigraphy#24]
Dear all,

Now that we have setup stable file-naming conventions, time is ripe, it seems, to merge all individual subfolders (named by encoders), that is transfer the XML files they contain into "XML-provisional", delete the now empty subfolders, and rename "XML-provisional" simply as "xml".
I guess you will have no difficulty to find your files as the K number is contained in their IDs.
This will greatly facilitate the management of github for Axelle.

Dear Axelle,
I guess it the easy way is that you take care of this action?

Dear Arlo,
Have we you got your green light?

Yours.

Manu

**Comment by arlogriffiths** [comment]
sorry for slow response. the merge has taken place a long time ago. the only thing that remains to be done, @michaelnmmeyer, is to rename the folder xml-provisional as per Manu's suggestion. Once that's done, you can close this.

copy to @chhomkunthea @chloechollet @salomepichon for their information. we'll all need to do a git pull once the renaming has been done.

**Comment by arlogriffiths** [comment]
@michaelnmmeyer : can you carry out this change now, let all concerned encoders know when they need to git pull, and close the issue?

**Comment by michaelnmmeyer** [comment]
Done
