### ISSUE TITLE
DHARMA_INSCIK00008- Zotero Short Title Isssue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#26]
dear @chhomkunthea, 

Can you check the Zotero Short Title `Malleret1963_01`? It matches 2 entries in Zotero Library _Notes archéologiques, II: Pierres gravées et cachets de divers pays du Sud-Est de l'Asie; III: Classification et nomenclature des « perles » archéologiques en fonction de la symétrie minérale_  and _L'archéologie du delta du Mékong_. 

Thanks

**Comment by arlogriffiths** [comment]
I’ll take care of this issue.

Le 13 avr. 2021 à 10:43, ajaniak ***@***.******@***.***>> a écrit :



dear @chhomkunthea<https://github.com/chhomkunthea>,

Can you check the Zotero Short Title Malleret1963_01? It matches 2 entries in Zotero Library Notes archéologiques, II: Pierres gravées et cachets de divers pays du Sud-Est de l'Asie; III: Classification et nomenclature des « perles » archéologiques en fonction de la symétrie minérale and L'archéologie du delta du Mékong.

Thanks

**Comment by chhomkunthea** [comment]
Ok! Many thanks!

**Comment by chhomkunthea** [comment]
I've changed the short title to Malleret1963_02 (for L'archéologie du delta du Mékong). Now the signal is green!

Thank you again!
