### ISSUE TITLE
DHARMA_INSCIK00003 - missing @source on reading

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#27]
dear @chhomkunthea, 

In your edition of K. 3, you have a reading without the `@source`, as per EGC it is required. Can you check if it can be added please? 
```
 <app loc="5">
                    <lem>śrīy<unclear cert="low">ā</unclear> me</lem>
                    <rdg>śrī <seg met="+"><gap reason="lost" quantity="1" unit="character"/></seg> me</rdg>
```
Thanks

**Comment by chhomkunthea** [comment]
I've corrected it! Now it's good. Thank you!
