### ISSUE TITLE
DHARMA_INSCIK00066 - use of attribute @status

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#28]
Dear @chhomkunthea, 

In your edition of K 66, you have encoded `<add place="below" status="unremarkable">` the attribute `@status` doesn't match EDD, can you update your encoding to the attribute `@rend` please?  

Thanks

**Comment by chhomkunthea** [comment]
It's done and now the file is green! Thank you!
