### ISSUE TITLE
DHARMA_INSCIK00121 - Zotero Short Title Issue

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#29]
Dear @chhomkunthea, 

In your edition of K 121, you have used the ZST `Finot1904_02` but it matches 2 entries in Zotero: _Nécrologie: prosper Odend'hal_ & _Notes d'épigraphie: VIII. Inscription de Prah That Kvan Pir_. Can you check this please? 

Thanks

**Comment by arlogriffiths** [comment]
I will take care of this.

however, @chloe and @kunthea: I fear you have no yet finished your zotero work, and/or have not being paying attention to possible duplication of short titles with items stored outside of the E-Cambodia folder. if the latter is true, it means you will both need to double check all zotero short titles in E-Cambodia to make sure the sort titles are unique in the entire DHARMA group library.




Le 13 avr. 2021 à 10:54, ajaniak ***@***.******@***.***>> a écrit :



Dear @chhomkunthea<https://github.com/chhomkunthea>,

In your edition of K 121, you have used the ZST Finot1904_02 but it matches 2 entries in Zotero: Nécrologie: prosper Odend'hal & Notes d'épigraphie: VIII. Inscription de Prah That Kvan Pir. Can you check this please?

Thanks

**Comment by chhomkunthea** [comment]
Dear Axelle and Arlo,

I see that there are indeed two short titles Finot1904_02 in the Zotero. The one we need is VIII. Inscription de Prah That Kan Pir. I think that we should correct its short title to Finot1904_06. I have tried to change it but the short title Finot1904_06 was accepted in the Oxygen. So I should wait for Arlo to set it right.  

I plan to check all the items in the folder E-Cambodia by the end of this month. While doing so, I will also check the possible duplication of short titles with items stored outside of the E-Cambodia folder.

Thank you!

**Comment by arlogriffiths** [comment]
I think the problem was the same as in the other case: your XML file did not validate in Oxygen because you hadn't adjusted the tag in zotero. Anyhow, I have now made the changes to distinguish Finot1904_06 from Finot1904_02, so that the file now validates.

I have simultaneously inserted some comments into the file for K. 121, marked with "argr2kuch". Please make the necessary changes in this file (and check all your other files on the same points) and then close this issue.

**Comment by chhomkunthea** [comment]
Yes, I've checked your comments in K.121 and made corrections. I'll check other files too. Thank you!
