### ISSUE TITLE
proper sign for virāma

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-khmer-epigraphy#36]
I see that some (or all?) of Chloé's files use ∙ instead of · (keyboard ABC extended option+shift+9) for virāma.

Please correct all cases in your files. Best to do so one by one, because • may also occur as punctuation sign. At least it does in the files of some other team members.

Please respond to this issue with "done" when you're done.

**Comment by arlogriffiths** [comment]
Is still still an issue?

@michaelnmmeyer : can you help check if ∙ occurs in any places right after a consonant and without `<g>` tag?

**Comment by michaelnmmeyer** [comment]
We have about a hundred occurrences in these files:

DHARMA_INSCIK00044.xml
> DHARMA_INSCIK00111.xml
> DHARMA_INSCIK00173.xml
> DHARMA_INSCIK00174.xml
> DHARMA_INSCIK00211.xml
> DHARMA_INSCIK00215.xml
> DHARMA_INSCIK00216-N1.xml
> DHARMA_INSCIK00216-N2.xml
> DHARMA_INSCIK00216-S.xml
> DHARMA_INSCIK00573.xml
> DHARMA_INSSiddham00192.xml


Le dim. 7 avr. 2024 à 05:33, arlogriffiths ***@***.***> a
écrit :

**Comment by arlogriffiths** [comment]
Thanks @michaelnmmeyer.

- [ ] @chhomkunthea : could you check all K. files listed by Michaël and convert any cases of • that represent virāma to ·, while implementing a suitable encoding with `<g>` in all other cases? Let me know if there are any cases where you hesitate about what is meant.

- [x] @danbalogh : can you check the case in Siddham00192?

Please check the checkbox when you're done, after which I'll close this issue.

**Comment by danbalogh** [comment]
In Siddham00192, the instance is in an XML comment that may in the course of time be converted into an apparatus note: "L4. G prints "Bappakah∙", which may have been meant for jihvāmūlīya, which is clear in the rubbing."
I think this should stay as is, and only instances of ∙ in the text of editions should be checked.

**Comment by chhomkunthea** [comment]
Dear Arlo,

I see that there are nine Cambodian inscriptions in the list. The two kinds of dot representing virāma look very similar on Oxygen Editor. I can manually replace the wrong dot with the right one. But I don’t understand about “implementing a suitable encoding with <g>”.

Best,
Kunthea

**Comment by arlogriffiths** [comment]
I mean that **if and only if** you find cases where ∙ is clearly not intended to represent virāma but rather represents a symbol, then you should replace it not by · but by `<g>` or `<g>.</g>` with appropriate @type inside `<g>` — in other words, you should then encode it following EGD 4.2.3 or 4.2.4 (gdoc version).

Is it clear now? Check the box above when you're done.

**Comment by danbalogh** [comment]
@chhomkunthea , if you have any difficulties with the encoding, you can also turn to me. I was planning to talk to you about some complex layouts sometime soon, after Michaël and I have discussed what would be the best strategy for going forward.

**Comment by chhomkunthea** [comment]
Yes, it is now clear. Thank you! I’ll start correcting the files soon.

Best,
Kutnhea

**Comment by chhomkunthea** [comment]
Thank you! Look forward to hearing from you about the complex layouts.

Best,
Kunthea
