### ISSUE TITLE
Doublons

### ISSUE THREAD

**Issue by michaelnmmeyer** [erc-dharma/tfc-khmer-epigraphy#37]
Duplicated files under `texts/xml-provisional/doublon-to-check` should be excluded from the repository (by adding this directory in .gitignore, for instance). Otherwise it's impossible to tell which files are supposed to be validated and which are not.

**Comment by arlogriffiths** [comment]
@michaelnmmeyer — this folder was created recently by @ajaniak when (at my request) she restructured the contents of the repo, which were previously organized per encoder. in the process, she determined that a small number of inscriptions had been encoded twice. see [this commit](https://github.com/erc-dharma/tfc-khmer-epigraphy/commit/c25acb92dbd9e3ee5473d07a324b2dcd90664790). 

our encoders @chhomkunthea, @chloechollet and @salomepichon are working on undoubling the files and will inform you once the doublon-to-check folder is ready to be deleted.

**Comment by michaelnmmeyer** [comment]
@arlogriffiths I understand. My observation is purely technical: I have a program that examines all repositories to find the texts edited so far and that performs some sanity checks, like checking for uniqueness. I made it ignore duplicate files for now.

**Comment by chloechollet** [comment]
The files have been undoubling by me and @chhomkunthea. I deleted the doublon-to-check folder.
