### ISSUE TITLE
Feedbacks on `*.txt`

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#4]
Dear all, 

I think I was able to align the plain text files. 

The line endings have been converted in LF. **Some CR might have survived my conversion routine**. Let me know and I will convert the file. 
Anyway avoid the mixed between, LF, CR and CRLF. Be careful while using your text editor.

Note that all the files in Doublons, Vacants and the K.1406 as well as K.1367 are in ASCII. I haven't change the format since the characters used are recognized (ASCII being a subset of UTF-8) and the use of the file won't necessitated such a precision in the encoding. It works so let's avoid creating new issue with it.

However some files still bear the sign of the forced conversion. When I could identify the original code of the character, I have ask for automatic changes, but in some cases, I couldn't. Could you look into: 
**K.315, K.364 and K.639 (same pattern)
K.1082
K.780 et K.937 (same pattern, not sure about the identification of the characters.)
K.1034**
and let me know what you expect!

**Comment by arlogriffiths** [comment]
**Réponse sur K. 315, K. 364 et K. 369**:  corrections faites.
@chhomkunthea : sais-tu qui est responsable des protions supplémentaires déchiffrées dans le fichier pour K. 315, par rapport à NIC II-III? Il faudrait si possible l'indiquer. Je crois qu'il y a encore des passages lisibles et il faudrait mettre à jour le système de translittération. Peux-tu t'en occuper?

**Réponse sur K. 1082**: corrections faites.

**Réponse sur K. 780 et K. 937**: corrections faites.

**Réponse sur K. 1034**: correction faite.

**Comment by arlogriffiths** [comment]
**Réponse sur K. 315, K. 364 et K. 369**:  corrections faites.
@chhomkunthea : sais-tu qui est responsable des protions supplémentaires déchiffrées dans le fichier pour K. 315, par rapport à NIC II-III? Il faudrait si possible l'indiquer. Je crois qu'il y a encore des passages lisibles et il faudrait mettre à jour le système de translittération. Peux-tu t'en occuper?

**Réponse sur K. 1082**: corrections faites.

**Réponse sur K. 780 et K. 937**: corrections faites.

**Réponse sur K. 1034**: correction faite.
