### ISSUE TITLE
replace "dDanda" by "ddanda"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-khmer-epigraphy#40]
@michaelnmmeyer — could you please make a global replacement of the `<g>` token "dDanda" by "ddanda"?

If you find other tokens in tfc-khmer-epigraphy that seem not to be compliant with the Symbol Taxonomy, as it stands now, please furnish a list.

**Comment by michaelnmmeyer** [comment]
OK for "dDanda". For symbols absent from the taxonomy, I will add warnings in the "errors" interface (https://dharmalekha.info/errors).

**Comment by arlogriffiths** [comment]
Thanks. Have you done git push?

**Comment by michaelnmmeyer** [comment]
Yes. This in fact concerned a single file which is not in this repository.

**Comment by arlogriffiths** [comment]
sorry, there are tokens beginning with dDanda (but not exclusively consisting in this string) that have escaped your attention. see Kunthea' most recent commit, where she manually corrected a number of cases.

![Two files · erc-dharmatfc-khmer-epigraphy@c711613 · GitHub](https://github.com/erc-dharma/tfc-khmer-epigraphy/assets/835603/c797f985-ea9e-403f-8ef1-27a71e2ea605)

**Comment by michaelnmmeyer** [comment]
Indeed, I likely did not check the proper directory. Fixed in 1b560d6bc825be24f486d0a800dd1fbfa9c58737.
