### ISSUE TITLE
K. 1354

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#5]
Dear @chloechollet, 

There are some `<persName>` inside your encoding of the K.1354. Arlo asked me to inform you that they need to be deleted. However if you want to keep them because of the research interest. I can show you how to handle your versions with Git Branches as well as write you as XSLT to make it easier for you to create those 2 versions: one without `<persName>` for the project and one with `<persName>` for your own purpose. 

Let me know.

Best, 
Axelle

**Comment by chloechollet** [comment]
I will remove those extra tags, but I would be indeed very pleased to have my own version of the files, for the research interest. Can you explain how to proceed ? Many thanks.

**Comment by arlogriffiths** [comment]
I am not sure I agree with creating two versions.

Eventually, we certainly do want to allow (and encourage) use of `<persName>`. Is it really necessary, Axelle, to forbid use of `<persName>` at this stage? EG 7.4 allows its use, so I think you have misinterpreted my intention when you write to Chloé: "Arlo asked me to inform you that they need to be deleted". Rather, what I meant is that Chloé needed to be reminded that use of `<persName>` is not mandatory at this stage.

**Comment by arlogriffiths** [comment]
so Chloé, don't remove any such tags just yet!

**Comment by ajaniak** [comment]
Yes, it is necessary to follow the encoding guide, it's its purpose. In order to be able to use and reuse, as well as query them, the files need to be harmonized. At least, try to be harmonized at TF level.
