### ISSUE TITLE
Question on K.1428

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#7]
Dear @chloechollet,

Some changes have been done regarding the encoding, especially on `<space>`used with `@unit='line | page'`. The `<space>`used in [K.1428](https://github.com/erc-dharma/tfc-khmer-epigraphy/blob/master/texts/xml-provisional/Chloe/K1428.xml) don't have attribute. Could you check them please? 

Let me know if you need help
Best

**Comment by arlogriffiths** [comment]
@chloechollet : could you take action? ask Axelle what needs to be done if you don't understand, or close this issue if you're already done.

**Comment by chloechollet** [comment]
Thanks Axelle. I checked and changed the <space> in the file !
