### ISSUE TITLE
Updating encoding : Line numbering

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfc-khmer-epigraphy#8]
Dear @erc-dharma/khmer-epigraphy, 

Daniel has updated the numbering pattern. The content of `@n` for `<lb/>`must be unique in the file. See EG, p. 21 for more informations. 
Could you please check the following files:
- @chloechollet : 
    - K0266
    - K0267
    - K0268
    - K1354
    - K1428

- @chhomkunthea: 
    - K1320

Let me know if you need help figuring out the new numbering pattern. 
Best,

**Comment by arlogriffiths** [comment]
please involve me too in determining the new numbering patterns

Le 24 mars 2020 à 16:50, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



Dear @erc-dharma/khmer-epigraphy<https://github.com/orgs/erc-dharma/teams/khmer-epigraphy>,

Daniel has updated the numbering pattern. The content of @n for <lb/>must be unique in the file. See EG, p. 21 for more informations.
Could you please check the following files:

  *   @chloechollet<https://github.com/chloechollet> :

     *   K0266
     *   K0267
     *   K0268
     *   K1354
     *   K1428
  *   @chhomkunthea<https://github.com/chhomkunthea>:

     *   K1320

Let me know if you need help figuring out the new numbering pattern.
Best,

**Comment by chhomkunthea** [comment]
Dear Axelle,

Thank you for sharing the comment from Daniel. I think that the K. 1320 has problem because, unlike in other inscriptions, I have not put A, B, C and D (the four faces of the stela) in front of the number of the line. For instance, I should have put A1 (instead of 1) for the first line of the face A. I will correct this.

Hope that everything is fine with you amid this coronavirus. Wish you all good luck!
Kunthea

**Comment by arlogriffiths** [comment]
@chhomkunthea : please confirm you have made that change in K1320.xml
@chloechollet : please confirm that you have made the changes that Axelle asked from you.

The last of you to two who responds may do so by pressing "close and comment", to close this issue.

**Comment by chhomkunthea** [comment]
Dear Arlo,

I have changed the line numbering by adding A, B , C and D.

Best,
Kunthea

**Comment by chloechollet** [comment]
I changed the line numbering in the different files too.
